package arraylistgui;


import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArrayListGUI.java
 *
 * Created on Oct 29, 2011, 1:49:00 PM
 */

/**
 *
 * @author andrea
 */
public class ArrayListGUI extends javax.swing.JFrame {

    private TableModelPersonagem tableModelDisciplina;

    /** Creates new form ArrayListGUI */
    public ArrayListGUI() {
        initComponents();
        tableModelDisciplina = new TableModelPersonagem();
        tableDisciplina.setModel(tableModelDisciplina);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpaneTable = new javax.swing.JScrollPane();
        tableDisciplina = new javax.swing.JTable();
        labelJogador = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelNota = new javax.swing.JLabel();
        textNota = new javax.swing.JTextField();
        buttonLimpar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        buttonInserir = new javax.swing.JButton();
        labelAno = new javax.swing.JLabel();
        labelProfissao = new javax.swing.JLabel();
        comboProfissao = new javax.swing.JComboBox();
        buttonAlterar = new javax.swing.JButton();
        textAno = new javax.swing.JTextField();
        LabelPersonagem = new javax.swing.JLabel();
        textP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        LabelLevel = new javax.swing.JLabel();
        textLevel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableDisciplina.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDisciplinaMouseClicked(evt);
            }
        });
        scrollpaneTable.setViewportView(tableDisciplina);

        labelJogador.setText("Jogador");

        labelNota.setText("Nota");

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        buttonInserir.setText("Inserir");
        buttonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserirActionPerformed(evt);
            }
        });

        labelAno.setText("Ano");

        labelProfissao.setText("Profissao");

        comboProfissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Polícia Militar", "ROTAM", "Exército", "PF", "Polícia Civil", "Comando Vermelho", "PCC", "Máfia" }));
        comboProfissao.setToolTipText("");
        comboProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProfissaoActionPerformed(evt);
            }
        });

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        LabelPersonagem.setText("Personagem");

        jLabel2.setText("Habilidade");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atirador", "Piloto", "Estrategista", "Atleta", "Inteligente" }));

        LabelLevel.setText("Level");

        textLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLevelActionPerformed(evt);
            }
        });

        jLabel4.setText("Cargo");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novato", "Membro", "Veterano", "Confiavel", "Braço Direito", "Líder" }));

        jLabel5.setText("Especialidade");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mecânico", "Médico", "Detetive", "Negociador" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpaneTable)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelAno)
                        .addGap(40, 40, 40)
                        .addComponent(textAno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInserir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelPersonagem)
                                    .addComponent(labelJogador)
                                    .addComponent(LabelLevel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textP, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelProfissao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(labelNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboProfissao, 0, 485, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAlterar, buttonInserir, buttonLimpar, buttonRemover});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJogador)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProfissao)
                    .addComponent(comboProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPersonagem)
                    .addComponent(textP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLevel)
                    .addComponent(textLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelNota)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInserir)
                    .addComponent(buttonRemover)
                    .addComponent(buttonLimpar)
                    .addComponent(buttonAlterar)
                    .addComponent(labelAno)
                    .addComponent(textAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        int index = tableDisciplina.getSelectedRow();
        if (index == -1)
            return;
        tableModelDisciplina.remove(index);
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private Personagem newFromGUI() {
        try {
            Personagem discip = new Personagem();
            discip.setAno(Integer.parseInt(textAno.getText()));
            discip.setProfissao(comboProfissao.getSelectedIndex()+1);
            discip.setJogador(textNome.getText());
            discip.setPersonagem(textP.getText());
            discip.setLevel(Integer.parseInt(textLevel.getText()));
            discip.setNota(Float.parseFloat(textNota.getText()));
            return discip;
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dado(s) de entrada invalido(s)!");
            return null;
        }

    }
    
    private void buttonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserirActionPerformed
        // TODO add your handling code here:
        Personagem discip = newFromGUI();
        if (discip != null)
            tableModelDisciplina.add(discip);
    }//GEN-LAST:event_buttonInserirActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        // TODO add your handling code here:
        int index = tableDisciplina.getSelectedRow();
        if (index == -1)
            return;
        Personagem discip = newFromGUI();
        if (discip != null)
            tableModelDisciplina.update(index, discip);
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        // TODO add your handling code here:
        textAno.setText("");
        textLevel.setText("");
        comboProfissao.setSelectedIndex(0);
        textNome.setText("");
        textP.setText("");
        textNota.setText("");
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void tableDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDisciplinaMouseClicked
        int index = tableDisciplina.getSelectedRow();
        if (index == -1)
            return;
        Personagem d = tableModelDisciplina.select(index);
        textAno.setText(Integer.toString(d.getAno()));
        textLevel.setText(Integer.toString(d.getLevel()));
        comboProfissao.setSelectedIndex(d.getProfissao()-1);
        textNome.setText(d.getJogador());
        textP.setText(d.getPersonagem());
        textNota.setText(Float.toString(d.getNota()));

    }//GEN-LAST:event_tableDisciplinaMouseClicked

    private void comboProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProfissaoActionPerformed

    private void textLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLevelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLevel;
    private javax.swing.JLabel LabelPersonagem;
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonInserir;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JComboBox comboProfissao;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelJogador;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelProfissao;
    private javax.swing.JScrollPane scrollpaneTable;
    private javax.swing.JTable tableDisciplina;
    private javax.swing.JTextField textAno;
    private javax.swing.JTextField textLevel;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNota;
    private javax.swing.JTextField textP;
    // End of variables declaration//GEN-END:variables

}
